baseURL = "https://tommcn.github.io/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Tomas McNamer"
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4
[params]
blogPageURL = "blog"
contactLink = "contact"
contactformURL = "mailto:tommcn@mcnamer.ca"
copyright = "All right reserved copyright © Portio 2022"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = ""
googleAnalytics = ""
logo = "images/site-navigation/logo.png"
[params.address]
address = ""
email = "tommcn@mcnamer.ca"
openingHours = ""
phone = ""
[params.map]
APIkey = ""
latitude = ""
longitude = ""
pinImage = ""
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/tomas-mc"
weight = 1
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/tommcn"
weight = 2
[[params.social]]
icon = "fa-envelope-square"
url = "mailto:tommcn@mcnamer.ca"
weight = 3
